#!/usr/bin/env python3
"""PULSIFY — seed.py  |  Run after schema.sql to populate database"""
import os, json, urllib.request, urllib.error
from pathlib import Path
from datetime import datetime, timedelta

env = {}
for p in ["/workspaces/Pulsify/.env", ".env"]:
    if Path(p).exists():
        for line in Path(p).read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
        break

URL = env.get("SUPABASE_URL", "https://cjzewfvtdayjgjdpdmln.supabase.co")
KEY = env.get("SUPABASE_SERVICE_KEY", "sb_secret_ZJa0UCrtdTUfFZT_p3zCfg_1m7F5QRf")

def ok(m): print(f"  OK   {m}")
def err(m): print(f"  ERR  {m}")
def days(n): return (datetime.now() + timedelta(days=n)).strftime("%Y-%m-%d")

def upsert(table, rows):
    all_keys = set()
    for r in rows: all_keys.update(r.keys())
    normalised = [{k: r.get(k) for k in all_keys} for r in rows]
    errors = []
    for i in range(0, len(normalised), 20):
        chunk = normalised[i:i+20]
        data = json.dumps(chunk).encode()
        req = urllib.request.Request(
            f"{URL}/rest/v1/{table}", data=data, method="POST",
            headers={"Content-Type":"application/json","apikey":KEY,
                     "Authorization":f"Bearer {KEY}","Prefer":"resolution=merge-duplicates,return=minimal"})
        try:
            with urllib.request.urlopen(req, timeout=30): pass
        except urllib.error.HTTPError as e:
            body = e.read().decode()
            errors.append(body[:100])
    if errors: err(f"{table}: {errors[0]}")
    else: ok(f"{table}: {len(rows)} rows upserted")

EVENTS = [
  {"id":"ev_amapiano_mabhida","source":"manual","name":"Amapiano Sundowner Vol.14","description":"KZN biggest amapiano night. Kabza De Small, DJ Maphorisa, open-air Moses Mabhida.","date_local":days(2),"time_local":"20:00","status":"onsale","venue_name":"Moses Mabhida Stadium","venue_city":"Durban","venue_address":"44 Isaiah Ntshangase Rd, Durban","venue_lat":-29.8280,"venue_lon":31.0341,"price_min":180,"is_free":False,"image_url":"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80","genre":"Amapiano","hype_score":97,"like_count":1842,"comment_count":94,"is_frontline":True,"frontline_rank":1,"commission_rate":8,"attendance_count":340,"organiser_name":"Moses Mabhida Events","lineup":["Kabza De Small","DJ Maphorisa","DJ Lag"],"dress_code":"Smart Casual","age_restriction":"18+"},
  {"id":"ev_gqom_eves","source":"manual","name":"Gqom Takeover — Eve's Lounge","description":"Legendary Gqom Takeover at Eve's Lounge Mthwalume. South Coast most hyped night.","date_local":days(1),"time_local":"21:00","status":"onsale","venue_name":"Eve's Lounge","venue_city":"South Coast","venue_address":"Mthwalume, KZN South Coast","venue_lat":-30.4850,"venue_lon":30.6280,"price_min":80,"is_free":False,"image_url":"https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80","genre":"Gqom","hype_score":97,"like_count":1180,"comment_count":84,"is_frontline":True,"frontline_rank":2,"commission_rate":8,"attendance_count":480,"organiser_name":"Eve's Lounge Mthwalume","lineup":["DJ Lag","Bello No Gallo","South Coast Residents"],"dress_code":"Anything goes","age_restriction":"18+"},
  {"id":"ev_beach_sessions","source":"manual","name":"Sunset Beach Sessions","description":"Free live music on the Durban beachfront every Saturday. Afro-soul, indie, acoustic.","date_local":days(4),"time_local":"16:00","status":"onsale","venue_name":"North Beach Promenade","venue_city":"Durban","venue_address":"North Beach, Marine Parade, Durban","venue_lat":-29.8619,"venue_lon":31.0423,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80","genre":"Live Music","hype_score":82,"like_count":608,"comment_count":29,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":156,"organiser_name":"North Beach Sessions","lineup":["The Soil","Ami Faku (support)"],"dress_code":"Beach casual","age_restriction":"All ages"},
  {"id":"ev_gqom_margate","source":"manual","name":"Margate Gqom Festival","description":"South Coast biggest gqom event. 3 floors, 10 DJs from raw gqom to afro-house.","date_local":days(5),"time_local":"20:00","status":"onsale","venue_name":"Galaxy Nightclub","venue_city":"Margate","venue_address":"Marine Drive, Margate, KZN","venue_lat":-30.8640,"venue_lon":30.3650,"price_min":150,"is_free":False,"image_url":"https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80","genre":"Gqom","hype_score":95,"like_count":1050,"comment_count":68,"is_frontline":True,"frontline_rank":3,"commission_rate":8,"attendance_count":820,"organiser_name":"Galaxy Nightclub","lineup":["Babes Wodumo","Mampintsha","DJ Lag","Distruction Boyz"],"dress_code":"All welcome","age_restriction":"18+"},
  {"id":"ev_sport_dolphins","source":"manual","name":"Dolphins vs Lions — T20 Cricket","description":"KZN Dolphins host the Lions at Kingsmead. Family-friendly.","date_local":days(2),"time_local":"14:00","status":"onsale","venue_name":"Sahara Stadium Kingsmead","venue_city":"Durban","venue_address":"Kingsmead, Durban","venue_lat":-29.8494,"venue_lon":31.0224,"price_min":80,"is_free":False,"image_url":"https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80","genre":"Sport","hype_score":79,"like_count":320,"comment_count":18,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":2800,"organiser_name":"CSA"},
  {"id":"ev_march_kzn","source":"manual","name":"South Coast Solidarity March","description":"Community-led march through Port Shepstone. Peaceful, permitted, families welcome.","date_local":days(1),"time_local":"09:00","status":"onsale","venue_name":"Port Shepstone Town Hall","venue_city":"South Coast","venue_address":"Bisset Street, Port Shepstone","venue_lat":-30.7389,"venue_lon":30.4521,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1568219656418-15c329312bf1?w=800&q=80","genre":"March","hype_score":65,"like_count":210,"comment_count":22,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":640,"organiser_name":"KZN Civil Society Forum"},
  {"id":"ev_joburg_amapiano","source":"manual","name":"Piano City Johannesburg","description":"Joburg premier amapiano festival. 5 stages across Maboneng. 40+ DJs. Food trucks and cocktail bars.","date_local":days(3),"time_local":"14:00","status":"onsale","venue_name":"Arts on Main","venue_city":"Johannesburg","venue_address":"264 Fox St, Maboneng, JHB","venue_lat":-26.2003,"venue_lon":28.0650,"price_min":200,"is_free":False,"image_url":"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80","genre":"Amapiano","hype_score":96,"like_count":2100,"comment_count":134,"is_frontline":True,"frontline_rank":4,"commission_rate":8,"attendance_count":3000,"organiser_name":"Maboneng Events"},
  {"id":"ev_soccer_fnb","source":"manual","name":"Soweto Derby — Chiefs vs Pirates","description":"The biggest match in African football at FNB Stadium. 90,000 capacity. Arrive early.","date_local":days(8),"time_local":"15:00","status":"onsale","venue_name":"FNB Stadium","venue_city":"Johannesburg","venue_address":"Soccer City Ave, Nasrec, JHB","venue_lat":-26.2348,"venue_lon":27.9813,"price_min":100,"is_free":False,"image_url":"https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80","genre":"Sport","hype_score":99,"like_count":5240,"comment_count":312,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":75000,"organiser_name":"PSL"},
  {"id":"ev_ct_jazz","source":"manual","name":"Cape Town International Jazz Festival","description":"Africa greatest jazz festival. 40 performances over 2 days. International and local acts.","date_local":days(5),"time_local":"16:00","status":"onsale","venue_name":"Cape Town ICC","venue_city":"Cape Town","venue_address":"1 Lower Long St, Cape Town","venue_lat":-33.9175,"venue_lon":18.4240,"price_min":500,"is_free":False,"image_url":"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80","genre":"Jazz","hype_score":96,"like_count":1890,"comment_count":124,"is_frontline":True,"frontline_rank":5,"commission_rate":8,"attendance_count":8000,"organiser_name":"CTIJF"},
  {"id":"ev_bloc_ct","source":"manual","name":"BLOC Cape Town — Season Opener","description":"Cape Town most celebrated club night. Boiler Room-style sets, world-class DJs.","date_local":days(3),"time_local":"22:00","status":"onsale","venue_name":"BLOC Cape Town","venue_city":"Cape Town","venue_address":"De Waterkant, Cape Town","venue_lat":-33.9200,"venue_lon":18.4170,"price_min":200,"is_free":False,"image_url":"https://images.unsplash.com/photo-1571266028243-d220c6a71ed9?w=800&q=80","genre":"Nightlife","hype_score":93,"like_count":1045,"comment_count":71,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":400,"organiser_name":"BLOC"},
  {"id":"ev_shisa_umlazi","source":"manual","name":"Umlazi Shisanyama Festival","description":"Annual shisanyama braai competition. 30+ vendors, live amapiano, gqom and maskandi.","date_local":days(7),"time_local":"10:00","status":"onsale","venue_name":"Umlazi Mega City","venue_city":"Durban","venue_address":"M18, Umlazi, Durban","venue_lat":-29.9700,"venue_lon":30.9000,"price_min":50,"is_free":False,"image_url":"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80","genre":"Shisanyama","hype_score":91,"like_count":987,"comment_count":52,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":440,"organiser_name":"Umlazi Events"},
  {"id":"ev_kirstenbosch","source":"manual","name":"Kirstenbosch Summer Concerts","description":"Open-air concerts against Table Mountain. BYO picnic. Dogs welcome.","date_local":days(7),"time_local":"17:00","status":"onsale","venue_name":"Kirstenbosch Botanical Gardens","venue_city":"Cape Town","venue_address":"Rhodes Dr, Newlands, Cape Town","venue_lat":-33.9883,"venue_lon":18.4323,"price_min":180,"is_free":False,"image_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80","genre":"Live Music","hype_score":89,"like_count":834,"comment_count":49,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":2000,"organiser_name":"SANParks"},
  {"id":"ev_soweto_shisa","source":"manual","name":"Soweto Shisanyama Festival","description":"Walter Sisulu Square. 50 vendors, traditional performances. Heritage day vibes.","date_local":days(4),"time_local":"10:00","status":"onsale","venue_name":"Walter Sisulu Square","venue_city":"Johannesburg","venue_address":"Klipspruit Valley Rd, Soweto","venue_lat":-26.2645,"venue_lon":27.8569,"price_min":60,"is_free":False,"image_url":"https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80","genre":"Shisanyama","hype_score":95,"like_count":1780,"comment_count":102,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":2000,"organiser_name":"Soweto Events"},
  {"id":"ev_afropunk_jhb","source":"manual","name":"AfroPunk Johannesburg","description":"Global AfroPunk festival hits JHB. Music, art, activism. Artists from across Africa and diaspora.","date_local":days(15),"time_local":"12:00","status":"onsale","venue_name":"Nasrec Expo Centre","venue_city":"Johannesburg","venue_address":"Nasrec, Johannesburg","venue_lat":-26.2380,"venue_lon":27.9790,"price_min":450,"is_free":False,"image_url":"https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80","genre":"Festival","hype_score":94,"like_count":1567,"comment_count":98,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":5000,"organiser_name":"AfroPunk"},
  {"id":"ev_jazz_joint","source":"manual","name":"Jazz on the Promenade","description":"Live jazz every Sunday at The Joint Jazz Cafe. Fresh seafood, craft beers, best jazz in KZN.","date_local":days(5),"time_local":"13:00","status":"onsale","venue_name":"The Joint Jazz Cafe","venue_city":"Durban","venue_address":"OR Tambo Parade, South Beach, Durban","venue_lat":-29.8700,"venue_lon":31.0440,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80","genre":"Jazz","hype_score":78,"like_count":423,"comment_count":18,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":95,"organiser_name":"The Joint Jazz Cafe"},
  {"id":"ev_hillcrest_mkt","source":"manual","name":"Hillcrest Farmers Market","description":"Every Saturday morning. 60+ stalls, fresh produce, artisan foods, crafts, live acoustic.","date_local":days(2),"time_local":"07:00","status":"onsale","venue_name":"Hillcrest Centre","venue_city":"Durban","venue_address":"Old Main Rd, Hillcrest","venue_lat":-29.7700,"venue_lon":30.7600,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80","genre":"Market","hype_score":68,"like_count":234,"comment_count":12,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":350,"organiser_name":"Hillcrest Market"},
  {"id":"ev_jacaranda_jazz","source":"manual","name":"Jazz in the Jacaranda City","description":"Annual jazz picnic under jacaranda trees at Pretoria Botanical Garden. Family-friendly.","date_local":days(7),"time_local":"11:00","status":"onsale","venue_name":"Pretoria Botanical Garden","venue_city":"Pretoria","venue_address":"2 Cussonia Ave, Brummeria, Pretoria","venue_lat":-25.7509,"venue_lon":28.2364,"price_min":80,"is_free":False,"image_url":"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80","genre":"Jazz","hype_score":74,"like_count":345,"comment_count":19,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":600,"organiser_name":"City of Tshwane"},
  {"id":"ev_sunset_cruise","source":"manual","name":"Durban Sunset Ocean Cruise","description":"2.5hr cruise across Durban Bay with live DJ, cocktails and Indian Ocean views.","date_local":days(6),"time_local":"17:30","status":"onsale","venue_name":"Durban Harbour Jetty","venue_city":"Durban","venue_address":"Bay of Plenty Jetty, Point Rd, Durban","venue_lat":-29.8720,"venue_lon":31.0480,"price_min":250,"is_free":False,"image_url":"https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80","genre":"Experience","hype_score":86,"like_count":527,"comment_count":33,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":60,"organiser_name":"Bay Charters Durban"},
  {"id":"ev_clifton_sunset","source":"manual","name":"Clifton Sunset Sessions","description":"Weekly sunset DJ sets at Clifton 4th Beach. Electronic and deep house. Free.","date_local":days(2),"time_local":"17:00","status":"onsale","venue_name":"Clifton 4th Beach","venue_city":"Cape Town","venue_address":"Clifton, Cape Town","venue_lat":-33.9436,"venue_lon":18.3762,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80","genre":"Electronic","hype_score":81,"like_count":478,"comment_count":28,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":300,"organiser_name":"Cape Sessions"},
  {"id":"ev_drakensberg","source":"manual","name":"Drakensberg Sunrise Hike and Braai","description":"Guided sunrise hike in uKhahlamba-Drakensberg. Ends with a braai overlooking the valley.","date_local":days(6),"time_local":"04:30","status":"onsale","venue_name":"Drakensberg Gardens Resort","venue_city":"Durban","venue_address":"Drakensberg, KwaZulu-Natal","venue_lat":-29.2700,"venue_lon":29.4500,"price_min":250,"is_free":False,"image_url":"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80","genre":"Experience","hype_score":88,"like_count":445,"comment_count":31,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":40,"organiser_name":"Drakenberg Adventures"},
]

BUSINESSES = [
  {"id":"biz_eyadini","name":"Eyadini Lounge","category":"shisanyama","tagline":"Umlazi's #1 Ekasi Shisanyama & Event Venue","description":"A dream that came to life in 2008. Hot gqom music, kwaito, deep house. Fresh food in the heart of Umlazi Township.","city":"Durban","suburb":"Umlazi","address":"3 Peace Rd, Umlazi, Durban, 4001","lat":-29.9630,"lon":30.9100,"phone":"+27 31 906 0100","website":"https://www.eyadini.co.za","rating":4.6,"review_count":1240,"price_range":"R","cover_image_url":"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80","is_frontline":True,"frontline_rank":1,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Mon-Thu","time":"11:00-22:00","open":True},{"day":"Fri","time":"11:00-02:00","open":True},{"day":"Sat","time":"10:00-02:00","open":True},{"day":"Sun","time":"10:00-20:00","open":True}]),"tags":json.dumps(["Live DJ","Gqom Music","VVIP Tables","Open Air","Parking"]),"gallery_urls":json.dumps(["https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80","https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&q=80"])},
  {"id":"biz_zabas","name":"Zaba's Shisanyama","category":"shisanyama","tagline":"Possibly the Best Braai in South Africa","description":"Went viral after Nick Hamman called it the best shisanyama in SA. Herb butter pap with Aromat is a taste revolution.","city":"Durban","suburb":"Mayville","address":"2 Johannes Nkosi Street, Mayville, Durban","lat":-29.8650,"lon":31.0020,"phone":"+27 31 202 1234","website":None,"rating":4.8,"review_count":890,"price_range":"R","cover_image_url":"https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&q=80","is_frontline":True,"frontline_rank":2,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Mon-Fri","time":"11:00-21:00","open":True},{"day":"Sat-Sun","time":"10:00-22:00","open":True}]),"tags":json.dumps(["Viral Spot","BYO Drinks","DJ Fridays","Outdoor Seating"])},
  {"id":"biz_joecools","name":"Joe Cools Beach Bar and Grill","category":"bar","tagline":"Durban's Iconic Beachfront Bar Since 1994","description":"Entertainment institution right on the beach. Upper deck overlooking the sea. Five bars. Lazy lunches or nightclub vibes.","city":"Durban","suburb":"North Beach","address":"137 OR Tambo Parade, North Beach, Durban","lat":-29.8619,"lon":31.0423,"phone":"+27 31 332 0977","website":"https://www.joecools.co.za","rating":4.1,"review_count":5028,"price_range":"RR","cover_image_url":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","is_frontline":True,"frontline_rank":3,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Mon-Fri","time":"11:00-Late","open":True},{"day":"Sat-Sun","time":"10:00-Late","open":True}]),"tags":json.dumps(["Ocean Views","5 Bars","Live DJ","Cocktails"])},
  {"id":"biz_oysterbox","name":"The Oyster Box Hotel","category":"hotel","tagline":"Iconic 5-Star Luxury Umhlanga Lighthouse","description":"One of South Africa most iconic luxury hotels beside the Umhlanga Lighthouse. World-class dining and legendary pool terrace.","city":"Durban","suburb":"Umhlanga","address":"2 Lighthouse Road, Umhlanga, Durban","lat":-29.7280,"lon":31.0862,"phone":"+27 31 514 5000","website":"https://www.oysterboxhotel.com","rating":4.9,"review_count":3210,"price_range":"RRRR","cover_image_url":"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Check-in","time":"14:00","open":True},{"day":"Restaurant","time":"06:30-22:00","open":True}]),"tags":json.dumps(["5-Star","Ocean Views","Pool","Fine Dining","Spa"])},
  {"id":"biz_eves","name":"Eve's Lounge","category":"club","tagline":"Mthwalume's Hottest Gqom and Nightlife Lounge","description":"The beating heart of South Coast nightlife. Weekend gqom nights, resident DJs, authentic KZN coastal vibe.","city":"South Coast","suburb":"Mthwalume","address":"Mthwalume, KZN South Coast","lat":-30.4850,"lon":30.6280,"phone":"+27 39 000 0010","website":None,"rating":4.7,"review_count":385,"price_range":"R","cover_image_url":"https://images.unsplash.com/photo-1571266028243-d220c6a71ed9?w=600&q=80","is_frontline":True,"frontline_rank":4,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Thu-Sat","time":"20:00-04:00","open":True},{"day":"Sun","time":"14:00-22:00","open":True},{"day":"Mon-Wed","time":"Closed","open":False}]),"tags":json.dumps(["Gqom","Live DJs","South Coast","VVIP Tables"])},
  {"id":"biz_galaxy","name":"Galaxy Nightclub","category":"club","tagline":"Margate's Premier Nightclub","description":"Multi-room venue with dedicated gqom, house, and hip-hop floors. Best sound system on the South Coast.","city":"Margate","suburb":"Margate","address":"Marine Drive, Margate, KZN, 4275","lat":-30.8640,"lon":30.3650,"phone":"+27 39 312 0010","website":None,"rating":4.4,"review_count":520,"price_range":"RR","cover_image_url":"https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Fri-Sat","time":"22:00-06:00","open":True},{"day":"Sun","time":"16:00-00:00","open":True}]),"tags":json.dumps(["Margate","Multi-Floor","Gqom","House","Hip-Hop"])},
  {"id":"biz_braai_republic","name":"Braai Republic Joburg","category":"shisanyama","tagline":"Joburg Home of the Braai Maboneng","description":"High-end shisanyama in the heart of Maboneng. Premium cuts, craft beer on tap, live DJs.","city":"Johannesburg","suburb":"Maboneng","address":"286 Fox St, Maboneng, Johannesburg","lat":-26.2003,"lon":28.0640,"phone":"+27 11 614 0900","website":None,"rating":4.7,"review_count":892,"price_range":"RR","cover_image_url":"https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80","is_frontline":True,"frontline_rank":5,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Wed-Thu","time":"12:00-22:00","open":True},{"day":"Fri-Sat","time":"12:00-00:00","open":True},{"day":"Sun","time":"11:00-20:00","open":True}]),"tags":json.dumps(["Craft Beer","Live DJ","Maboneng","Premium Braai"])},
  {"id":"biz_shimmy","name":"Shimmy Beach Club","category":"club","tagline":"Cape Town's Premier Beach Club","description":"Cape Town most iconic beach club. Resident DJs, private beach, cocktail pools, spectacular sunsets.","city":"Cape Town","suburb":"V&A Waterfront","address":"South Arm Rd, V&A Waterfront, Cape Town","lat":-33.9065,"lon":18.4205,"phone":"+27 21 200 7778","website":"https://www.shimmybeachclub.com","rating":4.4,"review_count":2340,"price_range":"RRR","cover_image_url":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Wed-Thu","time":"12:00-00:00","open":True},{"day":"Fri-Sat","time":"12:00-02:00","open":True},{"day":"Sun","time":"12:00-22:00","open":True}]),"tags":json.dumps(["Beach Club","Pool","DJ","Cocktails","Table Mountain"])},
  {"id":"biz_mzolis","name":"Mzoli's Place","category":"shisanyama","tagline":"Cape Town Most Famous Shisanyama Gugulethu","description":"World-famous shisanyama in Gugulethu. Choose your meat, they braai it. BYO drinks. A Cape Town institution.","city":"Cape Town","suburb":"Gugulethu","address":"NY 115, Gugulethu, Cape Town","lat":-33.9940,"lon":18.5480,"phone":"+27 21 638 1616","website":None,"rating":4.8,"review_count":1678,"price_range":"R","cover_image_url":"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Thu-Sun","time":"11:00-20:00","open":True},{"day":"Mon-Wed","time":"Closed","open":False}]),"tags":json.dumps(["BYOD","Outdoor","Iconic","Cape Township"])},
  {"id":"biz_truth_coffee","name":"Truth Coffee Roasting","category":"restaurant","tagline":"World Best Coffee Shop Cape Town CBD","description":"Voted world best coffee shop multiple times. Steampunk-themed, specialty coffee, breakfast and lunch.","city":"Cape Town","suburb":"CBD","address":"36 Buitenkant St, Cape Town CBD","lat":-33.9280,"lon":18.4200,"phone":"+27 21 200 0440","website":"https://www.truth.coffee","rating":4.8,"review_count":3456,"price_range":"RR","cover_image_url":"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Mon-Fri","time":"07:00-17:00","open":True},{"day":"Sat-Sun","time":"08:00-16:00","open":True}]),"tags":json.dumps(["World Best Coffee","Specialty","Steampunk","Breakfast"])},
  {"id":"biz_ogabazin","name":"Ogabazin Lounge","category":"bar","tagline":"Mthwalume's Chill Lounge and Party Spot","description":"Relaxed during the week, full party venue on weekends. Amazing cocktails and great local DJs.","city":"South Coast","suburb":"Mthwalume","address":"Mthwalume, KwaZulu-Natal South Coast","lat":-30.4820,"lon":30.6310,"phone":"+27 39 000 0011","website":None,"rating":4.5,"review_count":210,"price_range":"R","cover_image_url":"https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Tue-Thu","time":"17:00-01:00","open":True},{"day":"Fri-Sat","time":"16:00-04:00","open":True},{"day":"Sun","time":"12:00-22:00","open":True}]),"tags":json.dumps(["South Coast","Lounge","Local DJs","Cocktails"])},
  {"id":"biz_thejoint","name":"The Joint Jazz Cafe","category":"restaurant","tagline":"Shisanyama Jazz Craft Beer on the Promenade","description":"Contemporary shisanyama. Big Daddy Platter 1kg meat. Live jazz on weekends. Indian Ocean views.","city":"Durban","suburb":"South Beach","address":"OR Tambo Parade, South Beach, Durban","lat":-29.8700,"lon":31.0440,"phone":"+27 31 368 1062","website":None,"rating":4.7,"review_count":420,"price_range":"RR","cover_image_url":"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Tue-Thu","time":"12:00-22:00","open":True},{"day":"Fri-Sat","time":"12:00-00:00","open":True},{"day":"Sun","time":"10:00-20:00","open":True},{"day":"Mon","time":"Closed","open":False}]),"tags":json.dumps(["Live Jazz","Sea Views","Craft Beer","Shisanyama"])},
  {"id":"biz_marble","name":"Marble Restaurant and Bar","category":"restaurant","tagline":"Joburg Most Spectacular Rooftop Restaurant","description":"Wood-fired cooking with Joburg skyline views from Rosebank rooftop. Open-flame grills, premium SA wines.","city":"Johannesburg","suburb":"Rosebank","address":"Keyes Art Mile, Rosebank, Johannesburg","lat":-26.1440,"lon":28.0440,"phone":"+27 11 327 3420","website":"https://www.marble.restaurant","rating":4.7,"review_count":1456,"price_range":"RRR","cover_image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Mon-Sun","time":"12:00-23:00","open":True}]),"tags":json.dumps(["Rooftop","Wood-Fire","Skyline Views","Premium Wine"])},
  {"id":"biz_four_seasons","name":"The Four Seasons Westcliff Joburg","category":"hotel","tagline":"Johannesburg Most Iconic Luxury Hotel","description":"Terraced into the Westcliff hillside. Spectacular pool, fine dining, service that sets the standard.","city":"Johannesburg","suburb":"Westcliff","address":"67 Jan Smuts Ave, Westcliff, Johannesburg","lat":-26.1680,"lon":28.0260,"phone":"+27 11 481 6000","website":None,"rating":4.8,"review_count":987,"price_range":"RRRR","cover_image_url":"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Check-in","time":"15:00","open":True},{"day":"Restaurant","time":"06:30-22:00","open":True}]),"tags":json.dumps(["5-Star","Pool","Fine Dining","Zoo Views","Iconic"])},
  {"id":"biz_manaba","name":"Manaba Beach Lodge","category":"bnb","tagline":"Secluded Coastal Lodge Manaba Beach","description":"Right on Manaba Beach. Rock pools, pristine beaches, spectacular sunrises. Favourite for couples and families.","city":"South Coast","suburb":"Manaba","address":"Manaba Beach, South Coast, KZN","lat":-30.8800,"lon":30.3500,"phone":"+27 39 312 0030","website":None,"rating":4.8,"review_count":96,"price_range":"RR","cover_image_url":"https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80","is_frontline":False,"frontline_rank":None,"is_active":True,"is_verified":True,"hours":json.dumps([{"day":"Check-in","time":"13:00","open":True},{"day":"Check-out","time":"10:00","open":True}]),"tags":json.dumps(["Secluded","Rock Pools","Sunrise Views","Couples"])},
]

print(f"\n{'='*52}")
print(f"  PULSIFY SEEDER")
print(f"  Target: {URL}")
print(f"{'='*52}\n")

upsert("events", EVENTS)
upsert("businesses", BUSINESSES)

# Insert ticket tiers
TIERS = []
for ev in EVENTS:
    if not ev.get("is_free") and ev.get("price_min"):
        TIERS.append({"event_id":ev["id"],"name":"General Admission","price":ev["price_min"],"capacity":300,"sold":0,"sort_order":1})
        if float(ev["price_min"]) < 300:
            TIERS.append({"event_id":ev["id"],"name":"VIP Experience","price":float(ev["price_min"])*2,"capacity":50,"sold":0,"sort_order":2})

req = urllib.request.Request(
    f"{URL}/rest/v1/ticket_tiers",
    data=json.dumps(TIERS).encode(), method="POST",
    headers={"Content-Type":"application/json","apikey":KEY,"Authorization":f"Bearer {KEY}","Prefer":"return=minimal"})
try:
    with urllib.request.urlopen(req, timeout=30): ok(f"ticket_tiers: {len(TIERS)} tiers inserted")
except urllib.error.HTTPError as e:
    body = e.read().decode()
    if "duplicate" in body or "23505" in body: ok("ticket_tiers: already exist (skipped)")
    else: err(f"ticket_tiers: {body[:80]}")

print(f"\n{'='*52}")
print(f"  SEED COMPLETE")
print(f"  {len(EVENTS)} events | {len(BUSINESSES)} businesses")
print(f"{'='*52}\n")
