#!/usr/bin/env python3
"""PULSIFY — seed_more_events.py  |  Adds 30 more events to reach 50+ total"""
import os, json, urllib.request, urllib.error
from pathlib import Path
from datetime import datetime, timedelta

env = {}
for p in ["/workspaces/Pulsify/.env", ".env"]:
    if Path(p).exists():
        for line in Path(p).read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1); env[k.strip()] = v.strip()
        break

URL = env.get("SUPABASE_URL", "https://cjzewfvtdayjgjdpdmln.supabase.co")
KEY = env.get("SUPABASE_SERVICE_KEY")
if not KEY:
    print("ERR: SUPABASE_SERVICE_KEY not found in .env"); exit(1)

def ok(m): print(f"  OK   {m}")
def err(m): print(f"  ERR  {m}")
def days(n): return (datetime.now() + timedelta(days=n)).strftime("%Y-%m-%d")

def upsert(rows):
    all_keys = set()
    for r in rows: all_keys.update(r.keys())
    normalised = [{k: r.get(k) for k in all_keys} for r in rows]
    errors = []
    for i in range(0, len(normalised), 20):
        chunk = normalised[i:i+20]
        data  = json.dumps(chunk).encode()
        req   = urllib.request.Request(f"{URL}/rest/v1/events", data=data, method="POST",
            headers={"Content-Type":"application/json","apikey":KEY,
                     "Authorization":f"Bearer {KEY}","Prefer":"resolution=merge-duplicates,return=minimal"})
        try:
            with urllib.request.urlopen(req, timeout=30): pass
        except urllib.error.HTTPError as e:
            errors.append(e.read().decode()[:80])
    if errors: err(f"events: {errors[0]}")
    else: ok(f"events: {len(rows)} rows upserted")

MORE_EVENTS = [
  {"id":"ev_hip_hop_jhb","source":"manual","name":"SA Hip Hop Awards After-Party","description":"Official after-party. Cassper Nyovest, Nasty C, Focalistic performing live.","date_local":days(1),"time_local":"22:00","status":"onsale","venue_name":"Gallagher Convention Centre","venue_city":"Johannesburg","venue_address":"Gallagher Place, Midrand","venue_lat":-25.9700,"venue_lon":28.1190,"price_min":300,"is_free":False,"image_url":"https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80","genre":"Hip-Hop","hype_score":91,"like_count":1203,"comment_count":77,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":600,"organiser_name":"SA Music Awards"},
  {"id":"ev_food_trucks_jhb","source":"manual","name":"Joburg Food Truck Festival","description":"40 food trucks at Emmarentia Dam. Live music, craft beer, best street food in SA.","date_local":days(13),"time_local":"11:00","status":"onsale","venue_name":"Emmarentia Dam","venue_city":"Johannesburg","venue_address":"Emmarentia, Johannesburg","venue_lat":-26.1510,"venue_lon":28.0040,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80","genre":"Food","hype_score":78,"like_count":445,"comment_count":26,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":2000,"organiser_name":"Joburg Events"},
  {"id":"ev_rugby_jhb","source":"manual","name":"Lions vs Sharks — United Rugby","description":"United Rugby Championship at Ellis Park. Lions host the Sharks in KZN vs Gauteng battle.","date_local":days(10),"time_local":"16:00","status":"onsale","venue_name":"Ellis Park Stadium","venue_city":"Johannesburg","venue_address":"Doornfontein, Johannesburg","venue_lat":-26.2015,"venue_lon":28.0583,"price_min":180,"is_free":False,"image_url":"https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80","genre":"Sport","hype_score":86,"like_count":678,"comment_count":43,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":40000,"organiser_name":"SA Rugby"},
  {"id":"ev_woodstock_market","source":"manual","name":"Woodstock Exchange Night Market","description":"Monthly night market. 80+ vendors, street food, craft beer, live music. Free entry.","date_local":days(6),"time_local":"16:00","status":"onsale","venue_name":"Woodstock Exchange","venue_city":"Cape Town","venue_address":"66-68 Albert Rd, Woodstock, Cape Town","venue_lat":-33.9280,"venue_lon":18.4490,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80","genre":"Market","hype_score":80,"like_count":567,"comment_count":34,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":1000,"organiser_name":"Woodstock Market"},
  {"id":"ev_va_food","source":"manual","name":"V&A Food and Wine Experience","description":"Cape Town premium food festival. 100+ wine estates, gourmet stalls, celebrity chefs.","date_local":days(9),"time_local":"11:00","status":"onsale","venue_name":"V&A Waterfront","venue_city":"Cape Town","venue_address":"V&A Waterfront, Cape Town","venue_lat":-33.9023,"venue_lon":18.4208,"price_min":220,"is_free":False,"image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80","genre":"Food","hype_score":84,"like_count":623,"comment_count":37,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":5000,"organiser_name":"V&A Events"},
  {"id":"ev_ct_minstrels","source":"manual","name":"Cape Town Minstrel Carnival","description":"Iconic Minstrel Carnival. One of the world's great street festivals. Thousands in dazzling costumes.","date_local":days(13),"time_local":"09:00","status":"onsale","venue_name":"Green Point Track","venue_city":"Cape Town","venue_address":"Green Point, Cape Town","venue_lat":-33.9015,"venue_lon":18.4098,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80","genre":"Festival","hype_score":85,"like_count":567,"comment_count":41,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":10000,"organiser_name":"Cape Town Carnival"},
  {"id":"ev_bloc_pta","source":"manual","name":"BLOC PTA Red Night","description":"Pretoria hottest club night. Techno and house until 6AM. Past events have gone until 8AM.","date_local":days(3),"time_local":"22:00","status":"onsale","venue_name":"BLOC Club Arcadia","venue_city":"Pretoria","venue_address":"Arcadia, Pretoria","venue_lat":-25.7463,"venue_lon":28.2195,"price_min":150,"is_free":False,"image_url":"https://images.unsplash.com/photo-1571266028243-d220c6a71ed9?w=800&q=80","genre":"Nightlife","hype_score":91,"like_count":834,"comment_count":56,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":400,"organiser_name":"BLOC Pretoria"},
  {"id":"ev_tuks_party","source":"manual","name":"Tuks Res Wars Annual Party","description":"University of Pretoria biggest inter-res party. 4000 students. Multiple DJ stages.","date_local":days(2),"time_local":"20:00","status":"onsale","venue_name":"University of Pretoria","venue_city":"Pretoria","venue_address":"Lynnwood Rd, Hatfield, Pretoria","venue_lat":-25.7545,"venue_lon":28.2314,"price_min":70,"is_free":False,"image_url":"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","genre":"Student","hype_score":89,"like_count":1102,"comment_count":88,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":4000,"organiser_name":"UP SRC"},
  {"id":"ev_pe_jazz","source":"manual","name":"Ibhayi Jazz Festival Gqeberha","description":"Eastern Cape premier jazz festival. Free community day Saturday, ticketed gala Sunday.","date_local":days(9),"time_local":"14:00","status":"onsale","venue_name":"Boardwalk Convention Centre","venue_city":"Port Elizabeth","venue_address":"Marine Dr, Summerstrand, Gqeberha","venue_lat":-33.9800,"venue_lon":25.6600,"price_min":120,"is_free":False,"image_url":"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80","genre":"Jazz","hype_score":73,"like_count":287,"comment_count":14,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":500,"organiser_name":"PE Jazz Festival"},
  {"id":"ev_bloemfontein_piano","source":"manual","name":"Mangaung Amapiano Night","description":"Free State biggest piano event. 3 stages, local and national DJs, food market.","date_local":days(6),"time_local":"18:00","status":"onsale","venue_name":"Sand Du Plessis Theatre","venue_city":"Bloemfontein","venue_address":"Markgraaff St, Bloemfontein","venue_lat":-29.1200,"venue_lon":26.2140,"price_min":100,"is_free":False,"image_url":"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80","genre":"Amapiano","hype_score":76,"like_count":312,"comment_count":18,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":800,"organiser_name":"Mangaung Events"},
  {"id":"ev_sardine_run","source":"manual","name":"Sardine Run Festival Amanzimtoti","description":"Celebrate the world's greatest shoal. Live music, seafood market, surf competition.","date_local":days(12),"time_local":"08:00","status":"onsale","venue_name":"Amanzimtoti Beach","venue_city":"Durban","venue_address":"Amanzimtoti, South Coast","venue_lat":-30.0530,"venue_lon":30.8820,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80","genre":"Festival","hype_score":77,"like_count":445,"comment_count":22,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":5000,"organiser_name":"Sardine Run SA"},
  {"id":"ev_maskandi_durban","source":"manual","name":"Maskandi Kings Durban","description":"Celebrating the greatest maskandi artists. Traditional Zulu music at its finest.","date_local":days(10),"time_local":"14:00","status":"onsale","venue_name":"Durban ICC","venue_city":"Durban","venue_address":"45 Bram Fischer Rd, Durban","venue_lat":-29.8487,"venue_lon":31.0300,"price_min":120,"is_free":False,"image_url":"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80","genre":"Maskandi","hype_score":79,"like_count":412,"comment_count":23,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":320,"organiser_name":"Maskandi SA"},
  {"id":"ev_comedy_ct","source":"manual","name":"Comedy Nights at Mercury Live CT","description":"Cape Town funniest comedians every Thursday. 18+. Two drinks included with entry.","date_local":days(3),"time_local":"20:00","status":"onsale","venue_name":"Mercury Lounge Cape Town","venue_city":"Cape Town","venue_address":"43 De Villiers St, Cape Town","venue_lat":-33.9310,"venue_lon":18.4220,"price_min":100,"is_free":False,"image_url":"https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&q=80","genre":"Comedy","hype_score":77,"like_count":234,"comment_count":15,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":150,"organiser_name":"Mercury Live"},
  {"id":"ev_durban_marathon","source":"manual","name":"Durban City Marathon 2026","description":"Full, half and 10km routes through Durban. Medal and goodie bag. Start at Moses Mabhida.","date_local":days(14),"time_local":"05:30","status":"onsale","venue_name":"Moses Mabhida Stadium","venue_city":"Durban","venue_address":"44 Isaiah Ntshangase Rd, Durban","venue_lat":-29.8280,"venue_lon":31.0341,"price_min":150,"is_free":False,"image_url":"https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80","genre":"Sport","hype_score":72,"like_count":389,"comment_count":17,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":3400,"organiser_name":"Athletics SA"},
  {"id":"ev_wine_umhlanga","source":"manual","name":"Umhlanga Wine and Lifestyle Festival","description":"Premium wine tasting with 40 estates. Sunset views over the Indian Ocean from Oyster Box.","date_local":days(11),"time_local":"12:00","status":"onsale","venue_name":"The Oyster Box Hotel","venue_city":"Durban","venue_address":"2 Lighthouse Rd, Umhlanga","venue_lat":-29.7280,"venue_lon":31.0862,"price_min":350,"is_free":False,"image_url":"https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80","genre":"Lifestyle","hype_score":82,"like_count":398,"comment_count":22,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":120,"organiser_name":"Oyster Box Events"},
  {"id":"ev_ukzn_party","source":"manual","name":"UKZN SRC End-of-Term Party","description":"Biggest student event of the semester. 3 stages: amapiano, afrobeats, hip-hop. R60 before 10PM.","date_local":days(4),"time_local":"21:00","status":"onsale","venue_name":"UKZN Howard College","venue_city":"Durban","venue_address":"King George V Ave, Durban","venue_lat":-29.8680,"venue_lon":30.9840,"price_min":60,"is_free":False,"image_url":"https://images.unsplash.com/photo-1571266028243-d220c6a71ed9?w=800&q=80","genre":"Student","hype_score":90,"like_count":892,"comment_count":78,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":1200,"organiser_name":"UKZN SRC"},
  {"id":"ev_drag_durban","source":"manual","name":"Lipstick and Lashes Drag Extravaganza","description":"Durban biggest drag performance night. 15 artists competing. Full bar, costume contest. 18+.","date_local":days(8),"time_local":"20:00","status":"onsale","venue_name":"Chrome Nightclub","venue_city":"Durban","venue_address":"Florida Rd, Morningside, Durban","venue_lat":-29.8280,"venue_lon":30.9990,"price_min":100,"is_free":False,"image_url":"https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80","genre":"Nightlife","hype_score":80,"like_count":456,"comment_count":34,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":300,"organiser_name":"Chrome Nightclub"},
  {"id":"ev_ushaka_dive","source":"manual","name":"uShaka Night Dive Experience","description":"Night dive with whale sharks at uShaka Marine World. Fully guided, equipment provided.","date_local":days(6),"time_local":"19:00","status":"onsale","venue_name":"uShaka Marine World","venue_city":"Durban","venue_address":"1 Bell St, Point, Durban","venue_lat":-29.8672,"venue_lon":31.0585,"price_min":650,"is_free":False,"image_url":"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80","genre":"Experience","hype_score":85,"like_count":512,"comment_count":33,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":30,"organiser_name":"uShaka Marine World"},
  {"id":"ev_midrand_house","source":"manual","name":"Galaxy Club Deep House Saturday","description":"Deep house and Afro-house from sunset to sunrise. Galaxy Club Midrand. International selectors.","date_local":days(2),"time_local":"21:00","status":"onsale","venue_name":"Galaxy Club Midrand","venue_city":"Johannesburg","venue_address":"Midrand, Johannesburg","venue_lat":-25.9980,"venue_lon":28.1230,"price_min":120,"is_free":False,"image_url":"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80","genre":"Nightlife","hype_score":82,"like_count":523,"comment_count":29,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":400,"organiser_name":"Galaxy Midrand"},
  {"id":"ev_jhb_sandton_jazz","source":"manual","name":"Sandton Jazz Festival 2026","description":"Three days of world-class jazz in Sandton. Hugh Masekela tribute, orchestras, international acts.","date_local":days(6),"time_local":"17:00","status":"onsale","venue_name":"Sandton Convention Centre","venue_city":"Johannesburg","venue_address":"Maude St, Sandton","venue_lat":-26.1076,"venue_lon":28.0567,"price_min":350,"is_free":False,"image_url":"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80","genre":"Jazz","hype_score":87,"like_count":678,"comment_count":45,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":2000,"organiser_name":"Sandton Jazz"},
  {"id":"ev_braai_day_jhb","source":"manual","name":"National Braai Day Festival JHB","description":"Constitution Hill braai day. Heritage-themed, family-friendly. Free entry. Meat competitions.","date_local":days(11),"time_local":"11:00","status":"onsale","venue_name":"Constitution Hill","venue_city":"Johannesburg","venue_address":"1 Kotze St, Braamfontein","venue_lat":-26.1841,"venue_lon":28.0423,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80","genre":"Shisanyama","hype_score":86,"like_count":743,"comment_count":38,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":1500,"organiser_name":"National Braai Day"},
  {"id":"ev_afrobeats_durban","source":"manual","name":"AfroNation Durban Beach Edition","description":"Afrobeats, afropop and afro-house on the Durban beachfront. Live SA artists.","date_local":days(14),"time_local":"18:00","status":"onsale","venue_name":"Durban Exhibition Centre","venue_city":"Durban","venue_address":"45 Bram Fischer Rd, Durban","venue_lat":-29.8487,"venue_lon":31.0300,"price_min":220,"is_free":False,"image_url":"https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80","genre":"Afrobeats","hype_score":93,"like_count":1102,"comment_count":87,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":800,"organiser_name":"AfroNation SA"},
  {"id":"ev_oribi_zip","source":"manual","name":"Oribi Gorge Zip Line Adventure Day","description":"Thrilling zip lines, abseiling and the Lehr Waterfall trail at Oribi Gorge. Sunset braai included.","date_local":days(8),"time_local":"08:00","status":"onsale","venue_name":"Oribi Gorge Nature Reserve","venue_city":"South Coast","venue_address":"Port Shepstone, South Coast","venue_lat":-30.7000,"venue_lon":30.2700,"price_min":350,"is_free":False,"image_url":"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80","genre":"Experience","hype_score":85,"like_count":412,"comment_count":28,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":60,"organiser_name":"Wild5 Adventures"},
  {"id":"ev_ct_hip_hop","source":"manual","name":"Cape Town Hip-Hop Cypher","description":"Monthly freestyle cypher open to all. Battle rap, spoken word, live beats. Show up and spit.","date_local":days(4),"time_local":"18:00","status":"onsale","venue_name":"The Assembly","venue_city":"Cape Town","venue_address":"61 Harrington St, Cape Town","venue_lat":-33.9268,"venue_lon":18.4224,"price_min":50,"is_free":False,"image_url":"https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80","genre":"Hip-Hop","hype_score":76,"like_count":312,"comment_count":24,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":200,"organiser_name":"CT Hip-Hop Collective"},
  {"id":"ev_durban_film","source":"manual","name":"Durban International Film Festival","description":"Africa's longest-running film festival. International films, SA premieres, workshops.","date_local":days(15),"time_local":"09:00","status":"onsale","venue_name":"Gateway Theatre of Shopping","venue_city":"Durban","venue_address":"1 Palm Blvd, Umhlanga Ridge","venue_lat":-29.7330,"venue_lon":31.0700,"price_min":80,"is_free":False,"image_url":"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80","genre":"Arts","hype_score":71,"like_count":312,"comment_count":19,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":5000,"organiser_name":"DIFF"},
  {"id":"ev_gqom_eyadini2","source":"manual","name":"Gqom Nation Vol.2 — Eyadini Fridays","description":"Second instalment of the Eyadini Gqom Nation series. DJ Lag and Distruction Boyz.","date_local":days(9),"time_local":"21:00","status":"onsale","venue_name":"Eyadini Lounge","venue_city":"Durban","venue_address":"3 Peace Rd, Umlazi, Durban","venue_lat":-29.9630,"venue_lon":30.9100,"price_min":80,"is_free":False,"image_url":"https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80","genre":"Gqom","hype_score":92,"like_count":934,"comment_count":61,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":480,"organiser_name":"Eyadini Events"},
  {"id":"ev_amapiano_soweto","source":"manual","name":"Amapiano Sunday Sessions Soweto","description":"Sunday chill session at Vilakazi Street. Local amapiano DJs, food and family vibes.","date_local":days(5),"time_local":"12:00","status":"onsale","venue_name":"Vilakazi Street","venue_city":"Johannesburg","venue_address":"Vilakazi St, Orlando West, Soweto","venue_lat":-26.2645,"venue_lon":27.8569,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80","genre":"Amapiano","hype_score":82,"like_count":623,"comment_count":38,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":500,"organiser_name":"Soweto Live"},
  {"id":"ev_lifestyle_ct","source":"manual","name":"Cape Town Lifestyle and Wellness Expo","description":"Health, wellness, fitness and lifestyle brands. Yoga sessions, cooking demos, wellness talks.","date_local":days(11),"time_local":"09:00","status":"onsale","venue_name":"CTICC","venue_city":"Cape Town","venue_address":"1 Lower Long St, Cape Town","venue_lat":-33.9175,"venue_lon":18.4240,"price_min":80,"is_free":False,"image_url":"https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80","genre":"Lifestyle","hype_score":69,"like_count":234,"comment_count":12,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":3000,"organiser_name":"CT Expo Events"},
  {"id":"ev_food_market_kzn","source":"manual","name":"South Coast Food and Craft Market","description":"Best of KZN food and craft. Seafood, handmade crafts, live acoustic music.","date_local":days(5),"time_local":"09:00","status":"onsale","venue_name":"Hibberdene Beachfront","venue_city":"South Coast","venue_address":"Hibberdene Beach, KZN","venue_lat":-30.5780,"venue_lon":30.5740,"price_min":0,"is_free":True,"image_url":"https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80","genre":"Market","hype_score":77,"like_count":310,"comment_count":19,"is_frontline":False,"frontline_rank":None,"commission_rate":0,"attendance_count":440,"organiser_name":"South Coast Markets"},
  {"id":"ev_comedy_durban2","source":"manual","name":"Laugh Out Loud Durban Comedy Night","description":"KZN top comedians live at The Playhouse. Hosted by Celeste Ntuli. 18+. Two sets per night.","date_local":days(8),"time_local":"19:30","status":"onsale","venue_name":"The Playhouse Theatre","venue_city":"Durban","venue_address":"231 Anton Lembede St, Durban","venue_lat":-29.8567,"venue_lon":31.0228,"price_min":150,"is_free":False,"image_url":"https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&q=80","genre":"Comedy","hype_score":83,"like_count":367,"comment_count":21,"is_frontline":False,"frontline_rank":None,"commission_rate":8,"attendance_count":180,"organiser_name":"Playhouse Comedy"},
]

print(f"\n{'='*52}")
print(f"  PULSIFY — Extra Events Seeder")
print(f"  Adding {len(MORE_EVENTS)} events to reach 50+")
print(f"{'='*52}\n")

upsert(MORE_EVENTS)

print(f"\n{'='*52}")
print(f"  DONE — {len(MORE_EVENTS)} more events added")
print(f"  Total should now be 50+ events (5+ pages)")
print(f"{'='*52}\n")